// common: backward-compat re-export. New code imports from system/tokens.
export {
  pageHeading,
  pageSubheading,
  cardTitle,
  pageHeader,
  cardClass,
  tableClass,
  tableHeadClass,
  tableCellHead,
  tableCell,
  tableRowHover,
  emptyState,
  loadingState,
  formGroup,
  labelClass,
  inputClass,
  selectClass,
  formCardClass,
  buttonBase,
  buttonVariants,
  buttonSizes,
  btnClass,
  badgeBase,
  badge,
  statusColors,
  roleColors
} from '../system/tokens';
